name: unfollowerscurrent
description: VERDICT - Professional Follower Analyzer.
publish_to: 'none'
version: 6.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  shared_preferences: ^2.2.2
  http: ^1.6.0
  url_launcher: ^6.2.4
  google_mobile_ads: ^7.0.0
  package_info_plus: ^9.0.0
  flutter_local_notifications: ^17.2.4
  timezone: ^0.9.4
  app_tracking_transparency: ^2.0.5

  firebase_core: ^3.15.2
  firebase_analytics: ^11.3.1
  firebase_remote_config: ^5.1.3
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.12
  firebase_crashlytics: ^4.3.10
  webview_flutter_android: ^4.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
